- package-lock.json
- package.json
- tsconfig.json
package.json 추가
- `package.json` 추가
- PR 연동 테스트
- 기초 코드 테스트
- 이 PR 로 테스트를 진행합니다.
- 관련 이슈: #7
> feat: package.json 추가

- .env.example
- .gitignore
- package-lock.json
- package.json
- prisma/merge-schema.js
- prisma/models/car.prisma
- prisma/models/company.prisma
- prisma/models/contract.prisma
- prisma/models/contract_document.prisma
- prisma/models/customer.prisma
- prisma/models/file.prisma
- prisma/models/image.prisma
- prisma/models/meeting.prisma
- prisma/models/refresh_token.prisma
- prisma/models/user.prisma
- prisma/schema.prisma
Prisma /models 디렉토리 구성
- `/models` 디렉토리 생성
- 각 모델 기본 형태로 추가(id 만 추가되어 있음)
- `.gitignore` 에 관련 파일들 추가
- `.env.example` 추가
- `package.json` 에 관련 명령어 추가
```json
"prisma:build": "node prisma/merge-schema.js",
"prisma:migrate": "npm run prisma:build && npx prisma migrate dev", 
"prisma:studio": "npx prisma studio"
```
- `.env.example` 추가
.env.example 은 .env 에 어떠한 값들이 들어가는지 예시를 보여주는 파일입니다.
차후 .env 에 항목이 늘어나면 **반드시** `.env.example` 에도 항목을 추가하고, 어떤 값이 들어가야 하는지 공지 해줘야 합니다.
외부에 내부 비밀값들이 나가지 않기 위해서 `.env` 를 사용하는 것이기 때문에, `.env` 에 직접적인 값이 들어가는 건 가능한 지양하는 게 좋습니다!
단, `데이터베이스 경로` 처럼 개발 도중에는 로컬로 접근하는 주소는 유출되어도 무관하기 때문에 그대로 적습니다.
```env
DATABASE_URL="postgresql://admin:password@localhost:5432/carmate"
```
- 단일 schema.prisma 를 사용했을 때 발생하는 충돌을 방지하기 위해서 모델별로 나누어 작업합니다.
- 각자 API 를 개발하는 동안에는 본인의 모델 또는 관계성이 있는 …
> feat: Prisma /models 디렉토리 구성

- prisma/merge-schema.js
- prisma/models/car.prisma
- prisma/models/company.prisma
- prisma/models/contract.prisma
- prisma/models/contract_document.prisma
- prisma/models/customer.prisma
- prisma/models/file.prisma
- prisma/models/image.prisma
- prisma/models/meeting.prisma
- prisma/models/refresh_token.prisma
- prisma/models/user.prisma
- 관계형 설정 시에도 모델명 수정할 수 있도록 치환 범위를 전역으로 확장
- 개별 스키마 모델 관계 설정 시에도 모델명이 사용되어 변경이 필요함
1. 개별 스키마에서 관계 설정(1개 / N개)
2. 정상적으로 모델명 수정 확인
- 개별 스키마 관계 설정 시 `users UserModel[] ` 등으로 작성
- 참고 : https://github.com/jrkgus413/nb2-dearcarmate-team1/wiki/%5BPrisma%5D-%EC%8A%A4%ED%82%A4%EB%A7%88-%ED%98%91%EC%97%85-%EA%B0%80%EC%9D%B4%EB%93%9C
- 관련 이슈: #25
> [fix] 개별 스키마 모델명 변경 로직 수정 및 개별 스키마 모델명에 'Model' 접미사 추가

- .env.example
- .gitignore
- package-lock.json
- package.json
- prisma/models/contract-document.prisma.part
- src/app.ts
- src/controllers/images.controller.ts
- src/handlers/global-error.handler.ts
- src/handlers/not-found.handler.ts
- src/repositories/images.repository.ts
- src/routes/images.router.ts
- src/services/images.service.ts
- src/types/error.type.ts
- src/types/file.type.ts
- src/utils/error.util.ts
- src/utils/firebase.ts
- src/utils/from.util.ts
- src/utils/prisma.util.ts
images/upload 엔드포인트 작업
- 버그수정 : `contact-document.prisma.part` 에 있던 file 자료형 에러 수정
`Contract` -> `File`
- `images.router.ts`, `images.controller.ts`, `images.service.ts`, `images.repository.ts` 추가
- `multer` 패키지 설치
- `firebase-admin` 패키지 설치
- 구현에 필요한 기본적인 `util.ts`추가
수정 및 리팩토링이 필요할 수 있어, 논의 필요
- file 에서 사용할 `type.ts` 정의
- `Postman` 에서 테스트 할 수 있습니다.
**입력값**
**결과값**
실제로 사용하는 게 아니라면 크게 주의 사항은 없습니다.
차후, 프론트 연동 시 더 자세한 테스트를 진행 할 예정입니다.
- 관련 이슈: #34
> images/upload 엔드포인트 작업

- package-lock.json
- package.json
- prisma/models/car.prisma
- src/app.ts
- src/controllers/car.controller.ts
- src/repositories/car.repository.ts
- src/routes/car.router.ts
- src/services/car.service.ts
- src/types/car.type.ts
- `Car` 모델 및 관련 Prisma 스키마 정의 완료
- `car.route.ts` 라우터 정의 (CRUD + 확장 API)
- `car.controller.ts` 컨트롤러 작성 및 자리 마련
- `car.service.ts`, `car.repository.ts` 기능 구현
- 타입 정의: `car.type.ts` 작성
- 앱 라우터에 `/cars` 경로 등록 (`app.ts`)
- 차량 데이터를 생성, 조회, 수정, 삭제할 수 있도록 하기 위함
- 이후 대용량 업로드 및 모델 목록 조회 기능 확장을 위한 구조 선반영
- DB 마이그레이션 필요
- 관련 이슈: #30
> feat: Car API 등록/조회/수정/삭제 기능구현

- samples/customer-sample.csv
- src/types/customer.type.ts
- src/utils/parse.util.ts
feat: 대용량 업로드(고객) 유틸 구현
- 대용량 업로드(고객)을 위한 유틸리티 및 로직을 작성합니다.
- `고객명`, `성별`, `연락처`, `연령대`, `지역`, `이메일`, `메모`를 입력하여 고객 등록이 가능합니다.
- `연령대`, `지역`, `이메일`, `메모` 는 선택 사항입니다.
차후, 고객 API 가 올라오는 진행도에 따라서 유틸리티 적용 가능 유무가 정해집니다.
지금은 유틸리티만 구현합니다.
- `customer.type.ts` 이 추가 되었습니다.
- 해당 유틸 작성을 위해서 `CustomerCsvUploadRequest` 가 추가 되었습니다.
차후, `생성 요청 타입` 으로 바꾸거나 그대로 둬도 무방합니다.
- `parse.util.ts` 에 `csvToCustomerList` 가 추가 되었습니다.
- 향후 테스트를 위한 `customer-sample.csv` 가 추가 되었습니다.
- 기능 구현을 위한 유틸리티 작성
- 테스트 불가, 차후 고객 API  구현 진행에 따라 테스트 예정
- 이미 작업이 완료된 `/cars/upload` 엔드포인트를 참고해주세요.
- `미들웨어` 사용부터 `controller` - `service` - `repository` 까지의 흐름이 모두 구현되어 있습니다.
- 관련 이슈: #45
> feat: 대용량 업로드(고객) 유틸 구현

- src/controllers/company.controller.ts
- src/repositories/company.repository.ts
- src/routes/company.router.ts
- src/services/company.service.ts
- src/utils/db.util.ts
- prisma client 유틸리티 파일 경로 변경 
- db.util.ts 파일 삭제
- 클래스 기반 로직을 함수형 구조로 리팩토링
- prisma client 유틸 파일 통일
- 전체 코드 스타일 통일
- postman을 통한 api 호출 확인
- prisma client 유틸 파일 경로 확인
- 관련 이슈: #50
> refactor: 중복 함수 제거 및 전체 코드 스타일 통일

- prisma/models/user.prisma.part
[feat] Prisma User 스키마 파일 일부 수정 
- `user.prisma` 파일을 `.part` 파일로 분리
- Prisma 모델 관리 전략 일부 테스트
- User 모델에 대한 스키마 관리를 더 구조화하고자 분리 실험
- 팀 프로젝트 내 모델 관리 일관성 확보 목적
- `npx prisma format`으로 파일 유효성 검증
- 향후 통합 시 정상 마이그레이션 확인 예정
- 아직 `.part` 파일은 Prisma에서 직접 인식되지 않음
- 통합 작업 전 반드시 기존 스키마와 병합 필요
> feat: Prisma User 스키마 파일 일부 수정 

- src/routes/user.router.ts
- src/types/user.type.ts
- 유저 라우터 (`user.router.ts`) 정의
- 유저 응답/요청 타입 (`user.type.ts`) 정의
- 예시 : 로그인 기능 초기 개발
- 예시 : Prisma schema 수정
새로 타입과 라우터 만들었다 
---
---
----
> feat: 유저 라우터 및 타입 정의

- prisma/models/customer.prisma.part
- prisma의 Customer 스키마를 요구사항에 맞게 수정한다.
- 1. email, ageGroup, region에 ?를 추가
- 2. camelCase로 된 필드명에 `@map` 추가
- 3. 모델 이름을 `@@map`을 적용해서 소문자로 변경
- 4. gender, ageGroup, region에 varchar 적용
- 1. 기능 요구사항에 있는 고객 등록 요구사항을 만족하기 위함
- 2. camelCase로 하면 psql에서 테스트할 때, "(큰 따옴표)를 추가해줘야 함
- 3. 2번과 동일한 이유이다. 테이블에도 큰 따옴표를 추가해야 한다.
- 4. char로 지정하니까 API를 테스트할 때, 공백 문자가 추가되어 나온다.
- 관련 이슈: #93
> refactor: Customer 스키마 수정

- src/controllers/contract-document.controller.ts
- src/repositories/contract-document.repository.ts
- src/services/contract-document.service.ts
feat: 계약서 다운로드 작업
- `계약서 다운로드` 구현
- params 로 온 계약서 id 를 바탕으로 계약서를 찾은 다음에 "계약서 다운로드 성공" 만 반환합니다.
- 프론트 수정 후 기능 마자 구현 예정입니다.
- API 명세서에 따라 기능 구현
"계약서 다운로드 성공" 표시 확인 완료.
- 관련 이슈: #100
> feat: 계약서 다운로드 작업

- package.json
- prisma/models/user.prisma.part
- src/app.ts
- src/controllers/user.controller.ts
- src/repositories/company.repository.ts
- src/repositories/user.repository.ts
- src/routes/user.router.ts
- src/services/user.service.ts
> [권은혜] 회원가입 API구현 

- src/app.ts
- src/routes/user.router.ts
- src/services/company.service.ts
루트 라우터 미들웨어 `get` 으로 수정.
- `rootRouter` 를 라우터 미들웨어로 인식하도록 수정합니다.
- `app.ts` 의 `app.get('/', rootRouter);` 을 `app.use('/', rootRouter);`로 수정합니다.
- 바뀐 `User` 스키마에 맞춰서 `company.service.ts` 수정
```typescript
// L49 - L58
const formattedUsers = usersByCompany.map((user) => {
return {
id: user.id,
name: user.name,
email: user.email,
employeeNumber: user.employeeNumber,
phoneNumber: user.phoneNumber,
company: user.affiliatedCompany,
};
});
```
- 버그 수정
- 관련 이슈: #111
> fix: 루트 라우터 미들웨어 get 으로 수정

- package-lock.json
- package.json
- src/app.ts
- src/controllers/auth.controller.ts
- src/repositories/auth.repository.ts
- src/routes/auth.router.ts
- src/services/auth.service.ts
- src/utils/password.util.ts
feat: login 기능 구현
- `auth/` 라우터 미들웨어 구현
- `login` 엔드포인트(POST) 구현
- `cors` 패키지 추가
- `auth.router.ts`, `auth.controller.ts`, `auth.service.ts`, `auth.repository.ts` 추가
- API 구현
**POSTMAN**
**FRONTEND**
프론트엔드는 로그인 후 `/users/me(미구현)` 에 관한 에러가 뜨는 것이 현재 정상 동작입니다.
- 기본적인 기능만 포함되어 있습니다.
- 차후 `lastLoginAt` 과 같이 추가적인 기록이 들어갈 경우 `schema` 가 수정 될 가능성이 있습니다.
- 지금은 일단 일반 로그인이 가능한 상태 테스트 확인 후 올립니다.
- 관련 이슈: #123
> feat: login 기능 구현

- src/controllers/auth.controller.ts
- src/routes/auth.router.ts
- src/services/auth.service.ts
feat: 인증-리프레시 기능 구현
- 리프레시 API 구현
- `/refresh` 엔드포인트 추가
- API 문서에 따라 작성
**POSTMAN**
- 프론트엔드 에서는 시간이 지나야 동작하므로 켜두고 오래 기다려야 함.
- 현재 해당 기능이 동작할 때 까지 대기 중이며, 에러가 발생하면 그때 issue 로 수정할 예정.
- 관련 이슈: #129
> feat: 인증-리프레시 기능 구현

- src/controllers/car.controller.ts
- src/middlewares/allow.middleware.ts
- src/repositories/car.repository.ts
- src/routes/car.router.ts
- src/services/car.service.ts
- src/types/car.type.ts
- getUser가 동기 함수이므로 await getUser(req) → getUser(req)로 수정
- req.user 직접 접근한 부분(uploadCars)도 getUser(req)로 통일
- 컨트롤러 내부 코드 정리 및 역할 분리 강화
- 기존에 getUser를 비동기 함수처럼 잘못 사용하여 코드 일관성이 떨어짐
- 인증 유저 확인 방식이 req.user, getUser() 등 혼재되어 있어 유지보수에 불편함
- 유틸 함수로 통일해 예외 처리를 한 곳에서 처리하도록 개선
- 차량 등록 시 getUser 호출 후 정상 등록 확인
- getUser() 함수는 더 이상 await를 사용하지 않으며, 그에 따라 타입도 반영되어야 함
- 전체 컨트롤러에서 req.user 접근 방식이 바뀌었기 때문에 테스트 시 Authorization 헤더 필수
- 관련 이슈: #152
> [fix] getUser 비동기 호출 제거 및 req.user 처리 방식 통일

- prisma/models/alam.prisma.part
- prisma/models/contract-document.prisma.part
- prisma/models/contract.prisma.part
- prisma/models/meeting.prisma.part
- src/app.ts
- src/controllers/contract-document.controller.ts
- src/controllers/contracts.controller.ts
- src/repositories/contract-document.repository.ts
- src/repositories/contracts.repository.ts
- src/routes/auth.router.ts
- src/routes/contract-document.router.ts
- src/routes/contracts.router.ts
- src/services/auth.service.ts
- src/services/contract-document.service.ts
- src/services/contracts.service.ts
- src/types/contract.type.ts
- src/types/error.type.ts
계약서 목록, 업로드 프론트 연동 테스트 및 계약 생성, 계약 업데이트 API 구현
- `계약 생성` API 구현
- `계약 수정` API 구현
- 계약서 목록 테스트
- 계약서 업로드 테스트
- `계약 생성` API 구현
- 동일한 `차량` 에 계약이 생성 되지 못하도록 예외처리 되어 있습니다.
- 엮여 있는 항목이 많아서 트랜잭션으로 처리 되어 있습니다.
- `계약 수정` API 구현
- 동일하게 엮여 있는 항목이 많아서 트랜잭션을 사용해서 처리 되어 있습니다.
- 프론트 엔드 계약서 업로드 테스트를 위해 추가적으로 필요한 `계약 생성`, `계약 수정` 을 구현
**계약 생성**
**계약 수정**
**계약서 테스트**
- `Contract` 모델이 수정되었기 때문에 마이그레이션이 필요합니다.
- `계약 수정` 은 프론트에서 더 많은 테스트가 가능합니다.
- 단순히 계약서 업로드를 위한 부분과 간단한 테스트만 진행되었습니다.
- 코드가 효율적이지는 않습니다. 그냥 일단 생각나는 대로 동작에 집중해서 구현되어 있습니다.
- 굳이 트랜잭션 안에서 안해도 되는 로직이 있다거나 그런..?
- 관련 이슈: #149
> 계약서 목록, 업로드 프론트 연동 테스트 및 계약 생성, 계약 업데이트 API 구현

- src/controllers/customer.controller.ts
- src/repositories/customer.repository.ts
- src/services/customer.service.ts
- src/types/customer.type.ts
- 고객 API에서 soft delete를 추가한다.
- soft delete에 맞 고객 등록도 수정한다.
- 고객 API에서 고객 상세 정보 조회의 오류처리를 진행한다.
- repository 계층을 soft delete에 맞게 코드를 수정하였다.
- 관련된 service 계층 코드도 일부 수정되었다.
- 오류 처리가 안된 부분을 수정하였다. ( 고객 상세 정보 조회 )
- 관련 이슈: #147
> refactor: 고객 API 기능 수정 ( 프론트 엔드 테스트 )

- src/controllers/contracts.controller.ts
- src/repositories/contracts.repository.ts
- src/routes/auth.router.ts
- src/routes/contracts.router.ts
- src/services/contracts.service.ts
-  계약 삭제 API 추가
- 예시 : 사용자 회원가입 기능 초기 개발
- postman을 통한 테스트
- 관련 이슈: #160
> feat: 계약 삭제 API 구현

- .gitignore
- src/controllers/user.controller.ts
- src/repositories/user.repository.ts
- src/routes/user.router.ts
- src/services/user.service.ts
[feat] 회원 탈퇴 기능 구현 완성 
회원 탈퇴 기능 완성함 
----
---
회원가입 -> 로그인 -> 회원 탈퇴 순서로 테스트 함 
---
---
> [feat] 회원 탈퇴 기능 구현 완성 

- src/controllers/contracts.controller.ts
- src/repositories/contracts.repository.ts
- src/routes/contracts.router.ts
- src/services/contracts.service.ts
- 계약용 유저 목록 조회 API
- 병합
- postman을 사용한 테스트
- 관련 이슈: #167
> 계약용 유저 목록 조회

- src/utils/token.util.ts
fix: jwt expired 에러 수정
- `jwt expired` 에러가 뜨지 않도록 수정
- `iat(발급 시간)` 도 새로이 발급되도록 수정
- 리다이랙션 후 API 호출 시 에러 발생을 해결하기 위함
- 1시간 이후 리다이렉션 하고 나서 에러 발생하지 않음
- 관련 이슈: #181
> fix: jwt expired 에러 수정

- src/app.ts
- src/handlers/listen.handler.ts
feat: `리슨 핸들러` 추가
- 서버 실행시 서버가 구동하는 `IPV4` 표시
- `listenHandler` 가 추가되었습니다.
- VM 사용 시 서버가 구동되는 ip 를 표시하기 위함입니다.
- 프론트엔드 로그인 확인 완료
- 관련 이슈: #186
> feat: 리슨 핸들러 추가

- src/controllers/contracts.controller.ts
- src/repositories/contract-document.repository.ts
- src/repositories/contracts.repository.ts
- src/routes/contracts.router.ts
- src/services/contracts.service.ts
계약서 추가 시 계약 목록 표시 `soft delete` 적용
- 계약서 등록시 계약 목록 `soft delete` 한 계약 목록이 표시 됨
- `isDeleted: false`
- `deletedAt: null`
- `status` 도 `contractSuccessful` 인지 확인 하도록 수정
- `계약서 보드` 에서 `계약서 수정` 시 유저 목록 undefined 되는 버그 수정
```typescript
const where = {
companyId: BigInt(user.companyId),
userId: BigInt(user.id),
isDeleted: false,
deletedAt: null,
status: 'contractSuccessful',
documents: {
none: {},
},
};
```
`users` 로 불러오고 `user` 로 값을 가져오려고 해서 undefined 가 발생함
-> `userData` 로 변경하면서 정상적으로 유저 데이터 가져오도록 수정
```typescript
for (const userData of userList) {
formattedUserList.push({
id: userData.id,
// `: 백틱
data: `${userData.name}(${userData.email})`,
});
}
```
- 예시 : 사용자 회원가입 기능 초기 개발
- 예시 : 이메일 입력 / 비밀번호 미입력 시 에러 발생 확인
- 관련 이슈: #197
> fix: 계약서 추가 시 계약 목록 표시 soft delete 적용

- package-lock.json
- package.json
- src/controllers/car.controller.ts
- src/routes/car.router.ts
- car.controller.ts
- 차량 등록 필수값 검증 로직에서 accidentCount가 0인 경우 허용하도록 조건 수정
- 차량 목록 조회 시 status, carNumber, model 파라미터에 맞는 결과만 반환하도록 where 절 수정
- 사고 횟수가 0인 차량이 등록되지 않는 문제 해결
- 검색 시 전체 차량이 반환되는 문제 해결
- 차량 등록 시 accidentCount = 0 → 정상 등록
- 차량 번호로 검색 시 정확한 차량 1건만 반환
- 모델명 검색 시 해당 모델 차량만 반환
- 상태 필터링 시 해당 상태의 차량만 반환
- 관련 이슈: #203
> fix: 차량 등록 및 목록조회 문제 해결

- src/utils/from.util.ts
fix: url 표시 버그 수정
- 서버에서 에러 발생시 `url` 이 정상적으로 표시되도록 수정
```json
{
ip: '::1',
method: 'POST',
url: 'unknown',
status: '400',
createdAt: 2025-08-11T09:33:58.767Z
}
```
에서
```json
{
ip: '::1',
method: 'POST',
url: '/images/upload',
status: '400',
createdAt: 2025-08-11T09:33:58.767Z
}
```
으로 수정됨.
- 예시 : 사용자 회원가입 기능 초기 개발
- 예시 : 이메일 입력 / 비밀번호 미입력 시 에러 발생 확인
- 관련 이슈: #213
> fix: url 표시 버그 수정

- prisma/seed.ts
deleteMany 부분 주석 처리
- deleteMany 부분 주석 처리
- 관련 이슈: #231
> fix: deleteMany 부분 주석 처리

- src/repositories/customer.repository.ts
- src/services/customer.service.ts
- 비활성화 된 고객 정보는 받아들이지 않는다.
- 불필요한 코드인 repository 계층의 remove는 삭제합니다.
- 비활성화 고객은 conflict error로 처리합니다.
- 불필요한 코드인 remove 코드와 hard delete 관련 주석은 삭제되었습니다.
- 정확한 API 명세서 요구사항을 위해서
- 관련 이슈: #229
> refactor: 삭제된 고객 등록 시, 오류 발생 + repository remove 삭제

- package-lock.json
- package.json
- prisma/seed.ts
- prisma/seed.ts 신규 작성
- 8개 회사, 16명의 직원(남 10, 여 6)
- 59대 차량(브랜드·모델별 1대씩)
- 100명의 고객(성별·연령대 분포)
- 80건의 계약(성공/실패/차량확인/가격협의/계약서 작성 분포)
- 57개의 계약서 파일(File + ContractDocument)
- seed_assets/user_images.csv, seed_assets/car_images.csv를 읽어 DB에 이미지 연동
- 플랫폼 관리자 계정(admin@dearcarmate.com / admin1234) 생성
- package.json에 시드 실행 스크립트 추가
- 로컬/테스트 환경에서 즉시 사용 가능한 초기 데이터를 자동으로 세팅하여 프론트·백엔드 개발 및 테스트 효율 향상
- 이미지 파일 연동으로 프론트에서 UI 테스트 시 실 데이터와 유사한 환경 제공
- npm run db:seed 실행 후 DB에 데이터 생성 여부 확인
- 회사(8), 유저(17), 차량(59), 고객(100), 계약(80), 계약서(57) 건수 확인
- 이미지 URL이 User.image_url 및 Car.imageUrl에 정상 반영되는지 확인
- 프론트엔드 연동 후 로그인, 계약 목록, 차량 목록, 고객 목록 화면에서 정상 표시 여부 확인
- prisma/seed.ts 실행 시 DB 데이터가 초기화됨 (prisma migrate reset 사용 시 특히 주의)
- 관련 이슈: #238
> feat: seed 파일 생성

- prisma/seed.ts
- 예시 : 로그인 기능 초기 개발
- 예시 : Prisma schema 수정
- 예시 : 사용자 회원가입 기능 초기 개발
- 예시 : 이메일 입력 / 비밀번호 미입력 시 에러 발생 확인
- 관련 이슈: #
> fix: deleteMany 삭제

- README.md
docs: 팀원 별 구현 기능 상세 작성
- `팀원별 구현 기능 상세`의 본인 항목에 내용을 기입합니다.
- 관련 이슈: #242
> docs: 팀원별 구현 기능 상세 작성
